### ISSUE TITLE
Flatbase package has been skipped during composer install.

### ISSUE THREAD

**Issue by etemozdemirci** [bencagri/mokka#2]
Skipped installation of bin flatbase for package flatbase/flatbase: name conflicts with an existing file

**Comment by etemozdemirci** [comment]
I think I am having this problem regarding this issue. Any advice?

mokka git:(master) bin/mokka run --symbol=BNBBTC --interval=30 --test=true
PHP Warning:  file_put_contents(/Users/etem/mokka/src/Command/../../logs/2018-01-12): failed to open stream: No such file or directory in /Users/etem/mokka/vendor/flatbase/flatbase/src/Storage/Filesystem.php on line 39

Warning: file_put_contents(/Users/etem/mokka/src/Command/../../logs/2018-01-12): failed to open stream: No such file or directory in /Users/etem/mokka/vendor/flatbase/flatbase/src/Storage/Filesystem.php on line 39
PHP Warning:  chmod(): No such file or directory in /Users/etem/mokka/vendor/flatbase/flatbase/src/Storage/Filesystem.php on line 40

Warning: chmod(): No such file or directory in /Users/etem/mokka/vendor/flatbase/flatbase/src/Storage/Filesystem.php on line 40
SplFileObject::__construct(/Users/etem/mokka/src/Command/../../logs/2018-01-12): failed to open stream: No such file or directory

**Comment by bencagri** [comment]
Could you reinstall and run `composer install`again?
