### ISSUE TITLE
what should I do with this suggestions during composer install?

### ISSUE THREAD

**Issue by etemozdemirci** [bencagri/mokka#3]
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
react/event-loop suggests installing ext-libevent (>=0.1.0)
ratchet/pawl suggests installing reactivex/rxphp (~2.0)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
symfony/console suggests installing psr/log (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing symfony/process ()
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)

**Comment by bencagri** [comment]
They are just suggestions :)
