### ISSUE TITLE
Buy/sell function?

### ISSUE THREAD

**Issue by wisesiteguy** [bencagri/mokka#4]
Great script that has tested really well for me.

Not so much an issue, but just wondering if you'll update this so it actually buy/sells at some stage? Or, perhaps it should do that and something is wrong with my setup?  I've had a play about but I'm at best a php novice and it has me stumped...

**Comment by bencagri** [comment]
Hello @wisesiteguy 

Thanks for comment.

There is no buy and sell function for markets yet. If I can find any time, I will implement multiple markets.

**Comment by bencagri** [comment]
They have been added. #8af4424
