### ISSUE TITLE
wait time feature

### ISSUE THREAD

**Issue by Orbitalz-eth** [bencagri/mokka#8]
A nice feature would be a wait time feature. Such as for when we create a buy-limit and the buy-limit order isn't fulfilled within a certain amount of time, the bot will automatically cancel the buy-limit order and create a new one.

This feature would greatly reduce the number of stop-losses .

**Comment by bencagri** [comment]
I suppose this feature would be better for a certain strategy. With the current logic, you can do this with your own strategy. *Percent* strategy is just a sample. You can read config in any [strategy](https://github.com/bencagri/mokka/blob/master/src/Strategy/Indicator/Percent.php#L30).
