### ISSUE TITLE
Reset paramters

### ISSUE THREAD

**Issue by sifinz** [bencagri/mokka#9]
Hi, how to restart or stop the mokka program ? Also how to reset the parameters or go back to the initial screen where it asks you last buy/sell price ?

Also, why would I receive a "Filter Failure: Lot Size error" ?

Thanks

**Comment by bencagri** [comment]
Hi, if resetting parameters mean changing the [parameters](https://github.com/bencagri/mokka/blob/master/docs/02-parameters.md) with different symbol, you can check `--config` option. Create a new config file and pass it as option.

Buy/sell prices are set if there is no records in logs. If there is a record mokka uses that buy/sell record for the next move. If you reset it,just delete files under **logs** directory. It will ask you again.

Also, the [Lot Size Error ](https://www.google.com/search?q=Filter+Failure%3A+Lot+Size+error&ie=utf-8&oe=utf-8&client=firefox-b-ab) is a bug that I need to fix.

Cheers.
